### ISSUE TITLE
در نسخه نه کنترل کاربری که می سازیم خودش داده های خودش را فیلتر می کند 

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/sadafdashboard#141]
باید حتما یادمون باشه که ستثنا در فیلترشو تیک کنیم
لطفا پیش فرض استثنا در فیلتر کنترل کاربری فعال باشد

**Comment by azetroma** [comment]
تست شد و مشکلی مشاهده نشد. لطفا یک صفحه تست روی سایت دمو ساخته شود تا به صورت دقیقتر مشکل بررسی شود.
