### ISSUE TITLE
ایجاد گروه شاخص در قسمت تولید  نمودار

### ISSUE THREAD

**Issue by Mirahmadi** [azetroma/sadafdashboard#148]
گروه شاخص به قسمت ایجاد نمودار اضافه شود و با انتخاب هر گروه شاخص بصورت اتوماتیک شاخص ها و بعد های مربوط به آن گروه شاخص فیلتر گردند.

**Comment by azetroma** [comment]
در نسخه ۹.۲.۳ اضافه شده است
