### ISSUE TITLE
تکوین: برای فرمت فیلدهایی که فرمت آن تعیین نشده اند همانند گذشته عادی در نظر گرفته شوند

### ISSUE THREAD

**Issue by HaShamaei** [azetroma/sadafdashboard#152]

**Comment by azetroma** [comment]
به دلیل اینکه به صورت پیش فرض مقادیر عددی به صورت کاما نمایش داده می‌شوند در صورتی که در جدول نیز سال به صورت عددی باشد امکان تشخیص تفاوت میان عدد و سال نیست
